### ISSUE TITLE
Compiling requires GCC >= 5.0

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#1602]
As of 3eab1852 the code base no longer compiles with GCC 4.9, due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59987:
```
expr2java.cpp: In member function ‘virtual std::string expr2javat::convert_constant(const constant_exprt&, unsigned int&)’:
expr2java.cpp:285:15: error: ‘hexfloat’ is not a member of ‘std’
     buffer << std::hexfloat;
               ^
../common:214: recipe for target 'expr2java.o' failed
```

Either a workaround or an update of COMPILING.md are required.

**Comment by NlightNFotis** [comment]
@tautschnig Are there any consequences to just upgrading the compiler version requirement?

**Comment by tautschnig** [comment]
I think it's ok to upgrade.
