### PR TITLE
ANSI-C: Floating-point constant folding

### LINKED ISSUE #2583: Regression in goto-cc since PR #2490 switch-range was merged
The following example:

```
#define C1 (int) ( 0. / 1. + 0.5)
#define C2 (int) ( 1. / 1. + 0.5)

extern int g_c;
int g_out;

void main(void)
{
  switch (g_c)
  {
  case C1:
      g_out = 1;
      break;
  case C2:
      g_out = 2;
      break;
  default:
       break;
  }
}
```
Used to be able to be compiled by goto-cc, but since #2490 was merged this example now fails to compile due to a type check failure:

```
goto-cc test.c
test.c: In function 'main':
test.c:11:1: error: expected constant expression, but got `(signed int)(0.0 / 1.0 + 0.5)'
CONVERSION ERROR
```

### PR DESCRIPTION
**Pull request by kroening**
This allows constant-folding of expressions that use floating-point in the ANSI-C front-end. The specified rounding-mode is used.

Fixes #2583

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 171bf929406e60e0bdfa06182f91a1c7673a33f1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79229175
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

File: src/ansi-c/c_typecheck_expr.cpp [hunk 1]
```diff
@@ -3372,6 +3374,13 @@ void c_typecheck_baset::typecheck_side_effect_assignment(
 
 void c_typecheck_baset::make_constant(exprt &expr)
 {
+  // Floating-point expressions may require a rounding mode.
+  // The compile-time rounding mode may differ from the
+  // run-time rounding mode.
+  const auto rounding_mode =
+    from_integer(config.ansi_c.rounding_mode, signed_int_type());
+  adjust_float_expressions(expr, rounding_mode);
```
Comment (martin-cs) [inline src/ansi-c/c_typecheck_expr.cpp]:
```
// ISO 9899:1999
// 6.6.2 A constant expression can be evaluated during translation rather than runtime, and accordingly may be used in any place that a constant may be.
//
// F.7.2 During translation the IEC 60559 default modes are in effect:
// The rounding direction mode is round to nearest
```

I can't think of a way of changing the rounding mode during translation phase so this should be round to nearest (ties to even).

**Review by martin-cs — CHANGES_REQUESTED** [review]

File: src/ansi-c/c_typecheck_expr.cpp (hunk 1 above)
Comment (kroening) [reply src/ansi-c/c_typecheck_expr.cpp]: Say IBM's XL C let's you set the compile time rounding mode on the command line:
https://www.ibm.com/support/knowledgecenter/SSGH2K_11.1.0/com.ibm.xlc111.aix.doc/compiler_ref/opt_y_lower.html
But will change to "round to nearest".

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 8edc5ee762328b9a1f5397efc169512498e5d6e5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79291609

**Comment by martin-cs** [comment]
On Wed, 2018-07-18 at 06:54 +0000, Daniel Kroening wrote:
<snip>
> Say IBM's XL C let's you set the compile time rounding mode on the
> command line:
> https://www.ibm.com/support/knowledgecenter/SSGH2K_11.1.0/com.ibm.xlc
> 111.aix.doc/compiler_ref/opt_y_lower.html
> But will change to "round to nearest".

I didn't know it that had feature; feel free to leave as is if you
want.

**Review by martin-cs — APPROVED** [review]

File: src/goto-programs/adjust_float_expressions.cpp [hunk 2]
```diff
@@ -33,11 +31,11 @@ static bool have_to_adjust_float_expressions(
      expr.id()==ID_floatbv_typecast)
     return false;
 
-  const typet &type=ns.follow(expr.type());
+  const typet &type = expr.type();
```
Comment (hannes-steffenhagen-diffblue) [inline src/goto-programs/adjust_float_expressions.cpp:34]: Why is this follow not necessary (anymore)?

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]
LGTM

File: src/goto-programs/adjust_float_expressions.cpp (hunk 2 above)
Comment (kroening) [reply src/goto-programs/adjust_float_expressions.cpp:34]: This hasn't been necessary for many years (ever since typedefs get expanded immediately).

**Review by tautschnig — APPROVED** [review]
Looks good to me, but really approving because @martin-cs has approved.
