### PR TITLE
Ensure floating-point literals preserve distinction between types with same representation

### LINKED ISSUE #3271: Regression test ansi-c/float_constant1 is failing on develop
The test `regression/ansi-c/float_constant1` gives me this output:

```
main.c:16:1: error: array size must not be negative, but got -1
 STATIC_ASSERT(__builtin_types_compatible_p(_Float32, __typeof(1.0f32)));
CONVERSION ERROR
EXIT=1
SIGNAL=0
```

This worked before 72957a9128d597e3d2f315df39f5396232f2a53c (which does make changes relating to floating point numbers, but nothing that immediately jumps out as "wrong" to me)

Note that so far I've only seen this happen on machines that have upgraded to Ubuntu 18.04, so maybe this is related to different versions of the default gcc being visible? (`gcc` itself has no issue with `_Float32`, i.e.
```
_Static_assert(__builtin_types_compatible_p(_Float32, __typeof(1.0f32)), "Floating point numbers should work");
``` 
compiles fine with gcc)

### PR DESCRIPTION
**Pull request by smowton**
For example, `_Float32 `and `float` are bitwise identical but must be distinguished by `__builtin_types_compatible`.

Bug introduced by https://github.com/diffblue/cbmc/commit/72957a9128d597e3d2f315df39f5396232f2a53c (thanks @hannes-steffenhagen-diffblue), spotted by test `ansi-c/float_constant1`, missed in CI because only evident with GCC >= 7 (requires `_Float32` et al to be real types). Fixes #3271.

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]
Yep, that fixes it :)

**Review by NlightNFotis — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: df1c57be2e0962f5b8e159efd5846faac460ff30).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90303412

**Comment by martin-cs** [comment]
Late to the party pedantry : ISO-9899 does not guarantee the association between ```float``` and IEEE-754's ```binary_32``` so, depending on when the architecture specific things get fixed, this is the right thing to do.

**Comment by smowton** [comment]
Fortunately that was just an example -- the type used will be whatever the constant literal specifies, in this particular case using an `f32` suffix to insist on `_Float32`, cf. `f` for `float`. I suppose technically `ieee_floatt` isn't making a `float` then, but rather an anonymous type with 23/8 bits of mantissa/exponent respectively, which happens to be the same representation we use for `float`.

**Comment by martin-cs** [comment]
I meant that in a positive way; I think the change helps improve things.
