### PR TITLE
Provide implementations of __builtin_ia32_vec_ext_*

### LINKED ISSUE #5903: Compilation errors with SIMD libraries in different platforms
CBMC version: 5.24
Operating system: macOS 10.15 / Ubuntu 20.04
Exact command line resulting in the issue: `goto-cc simd.c` where simd.c contains the program
```
#include <immintrin.h>
#include <assert.h>

int main() {
    __m128i values = _mm_setr_epi32(0x1234, 0x2345, 0x3456, 0x4567);
    int val1 = _mm_extract_epi32(values, 0);
    assert(val1 == 0x1234);
    return 0;
}
```
What behaviour did you expect: Successful compilation.
What happened instead:

Got the following error on macOS 10.15:
```
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/avx512fintrin.h: In function '_mm512_sqrt_pd':
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/avx512fintrin.h:1503:1: error: wrong number of function arguments: expected 1, but got 2
   return (__m512d)__builtin_ia32_sqrtpd512((__v8df)__A,
CONVERSION ERROR

```
and the following error on Ubuntu 20.04:
```
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h: In function '_mm512_reduce_add_epi32':
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:15496:1: error: in expression '__builtin_shuffle(__T6, { 2, 3, 0, 1 })':
conversion from 'signed int' to '__gcc_v4si': implicit conversion not permitted
   __MM512_REDUCE_OP (+);
CONVERSION ERROR
```

### PR DESCRIPTION
**Pull request by tautschnig**
These built-ins extract an element of a vector.

Fixes: #5903

~Includes #5913, and will remain a Draft until that PR is merged.~

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: regression/cbmc/SIMD1/test.desc [hunk 1]
```diff
@@ -0,0 +1,8 @@
+CORE gcc-only broken-smt-backend
```
Comment (kroening) [inline regression/cbmc/SIMD1/test.desc]: Still broken after #5974? Also, there is an `#ifdef _MSC_VER` in the test, which suggests it might work on Visual Studio?

**Review by kroening — APPROVED** [review]

File: regression/cbmc/SIMD1/test.desc (hunk 1 above)
Comment (tautschnig) [reply regression/cbmc/SIMD1/test.desc]: The SMT conversion still fails (at `src/solvers/smt2/smt2_conv.cpp:2531 function: convert_typecast`), but Visual Studio should indeed be ok. Fixed.
