### PR TITLE
Stop building memory-analyzer on Mac and Windows

### LINKED ISSUE #7922: Build fails on Apple Silicon
CProver build fails when executing the `memory-analyzer` subtask on Apple Silicon (using CMake).

Specifically the error is:
```
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:316:4: error: malloc calling conventions not know for current platform
#  error malloc calling conventions not know for current platform
   ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:324:3: error: use of undeclared identifier 'record'
  record = get_most_recent_record("*stopped");
  ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:325:46: error: use of undeclared identifier 'record'
  auto frame_content = get_value_from_record(record, "frame");
                                             ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:336:5: error: use of undeclared identifier 'record'
    record = get_most_recent_record("*stopped");
    ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:341:3: error: use of undeclared identifier 'record'
  record = get_most_recent_record("^done", true);
  ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:342:39: error: use of undeclared identifier 'record'
  allocated_memory[get_register_value(record)] = allocated_size;
                                      ^
/Users/esteffin/git/cbmc/src/memory-analyzer/gdb_api.cpp:342:50: error: use of undeclared identifier 'allocated_size'
  allocated_memory[get_register_value(record)] = allocated_size;
```

The offending changes have been introduced in `c1f9237e36d09d47eb58f2c191b5edf2f9bc1a7c` and part of PR (https://github.com/diffblue/cbmc/pull/7756) at https://github.com/diffblue/cbmc/pull/7756/commits/c1f9237e36d09d47eb58f2c191b5edf2f9bc1a7c#diff-528c73e43b559ab716b320cc9945a0d95c99ea6b5de697f0e0e6910644775cfdR290.

Specifically in `src/memory-analyzer/gdb_api.cpp:290` the variable `record` and `allocated_size` declaration have been guarded by `__x86_64__` and `__i386__`, so on Apple Silicon (that is not `__x86_64__` nor `__i386__`) the build fail at line `316` because of `#  error malloc calling conventions not know for current platform` and subsequently with undefined variables.

CBMC version: `develop`
Operating system: MacOS Ventura on Apple Silicon
Exact command line resulting in the issue: `cmake ..` and then `make` or `make memory-analyzer`
What behaviour did you expect: successful build
What happened instead: build failure

### PR DESCRIPTION
**Pull request by esteffin**
This PR fixes an issue when trying to build `memory-analyzer` on Apple Silicon machines by excluding it on Windows and Apple systems.

This also was the expected behaviour for it.

Fixes Issue https://github.com/diffblue/cbmc/issues/7922

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by TGWDB — APPROVED** [review]

**Review by tautschnig — COMMENTED** [review]
Can we please also change `src/Makefile` to do

```
ifeq ($(WITH_MEMORY_ANALYZER),1)
  all: memory-analyzer.dir
else ifneq ($(filter-out Windows Darwin,$(detected_OS)),)
  all: memory-analyzer.dir
endif
```

instead of the current Linux-only logic?

**Comment by thomasspriggs** [comment]
Should this be built for Apple + Intel builds?

**Comment by tautschnig** [comment]
> Should this be built for Apple + Intel builds?

macOS has lldb instead of gdb, and I have no idea whether our interface with gdb ports to that. So I'd say no. (But of course someone could sit down and try and make this work...)

**Review by tautschnig — APPROVED** [review]

**Comment by esteffin** [comment]
> Should this be built for Apple + Intel builds?

Even if the module is not enabled by default, it is possible to compile it in any system by using `WITH_MEMORY_ANALYZER`

**Comment by NlightNFotis** [comment]
`lldb` to my knowledge uses different commands than `gdb`, so making it work is a fairly elaborate exercise.

We probably shouldn't consider it as part of this change.
