### ISSUE TITLE
Regression in goto-cc since PR #2490 switch-range was merged

### ISSUE THREAD

**Issue by chrisr-diffblue** [diffblue/cbmc#2583]
The following example:

```
#define C1 (int) ( 0. / 1. + 0.5)
#define C2 (int) ( 1. / 1. + 0.5)

extern int g_c;
int g_out;

void main(void)
{
  switch (g_c)
  {
  case C1:
      g_out = 1;
      break;
  case C2:
      g_out = 2;
      break;
  default:
       break;
  }
}
```
Used to be able to be compiled by goto-cc, but since #2490 was merged this example now fails to compile due to a type check failure:

```
goto-cc test.c
test.c: In function 'main':
test.c:11:1: error: expected constant expression, but got `(signed int)(0.0 / 1.0 + 0.5)'
CONVERSION ERROR
```

**Comment by chrisr-diffblue** [comment]
The closed/abandoned PR https://github.com/diffblue/cbmc/pull/2076 and/or the merged PR https://github.com/diffblue/cbmc/pull/2081 may have some hints as to how to solve this.

**Comment by tautschnig** [comment]
Maybe we shouldn't strictly require that the result is a single constant, and instead accept expressions that solely consist of constants (and type casts).

**Comment by chrisr-diffblue** [comment]
That would be one option - though it seems theres a number of places that we've recently tripped over cases where this kind of constant FP operation isn't currently handled - so maybe we really should attempt a better fix to `simplify()` to handle this kind of expression?

**Comment by tautschnig** [comment]
Sure, if we can fix `simplify()` then that's even better!

**Comment by chrisr-diffblue** [comment]
I won't get chance to look this week, but I'll see if I can make some time next week...
