### PR TITLE
Add support for building with GCC 14

### LINKED ISSUE #7749: Compilation Error due to danling-reference warning with -Werror
Pulling the develop branch and change into cbmc directory and executing the following commands:
```
git submodule update --init
cmake -S . -Bbuild
cd build
make
```
I get the following errors:

`.../cbmc/src/goto-symex/goto_symex.cpp:350:18: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  350 |   const symbolt &return_symbol = get_fresh_aux_symbol( 
...`

and

`
.../cbmc/src/solvers/smt2/smt2_conv.cpp:998:37: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  998 |   for(auto ch : id2string(identifier))
`
I suspect these are not the only errors if I did not abort the compilation.

After adding  "-Wno-dangling-reference" I got the following errors:
`.../src/util/cmdline.h:75:16: error: ‘virtual bool cmdlinet::parse(int, const char**, const char*)’ was hidden [-Werror=overloaded-virtual=]
   75 |   virtual bool parse(int argc, const char **argv, const char *optstring);`

Working with linux6.3-4-1 Manjaro and GCC 13.1.1

### PR DESCRIPTION
**Pull request by tautschnig**
GCC 14 adds new warnings. Those are largely spurious (perhaps with exception of the interpreter code), but still require working around. These warnings also affect CaDiCaL builds, which in turn requires us to upgrade to version 2.0.0, where workarounds have been added.

Fixes: #7749

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
It seems the analysis trips over local namespacet and irep_idt instances, which are harmless, but it can't know that.

**Review by TGWDB — APPROVED** [review]

**Review by remi-delmas-3000 — APPROVED** [review]
