### ISSUE TITLE
goto-gcc fails to compile simple C program - Conversion error

### ISSUE THREAD

**Issue by F3real** [diffblue/cbmc#5153]
Trying to compile following code fails with conversion error:
```c
#include <stdio.h>

typedef struct rcolor_t {
	unsigned char attr;
} RColor;

#define RCOLOR(a) (RColor) {a}
#define RColor_RED        RCOLOR(0x01)

int main() {
  RColor rcolor;
  rcolor = (RColor) RColor_RED;

  printf("Resut is %X\n", rcolor.attr);
}
```
Resulting output:
```
example.c: In function 'main':
example.c:12:1: error: type cast to 'struct rcolor_t { unsigned char attr; }' is not permitted
   rcolor = (RColor) RColor_RED;
CONVERSION ERROR
```

Program compiles fine with **gcc 9.1.0**. 
Example may look a bit contrived but it is simplified testcase of issue I encountered trying to run CBMC on [radare](https://github.com/radareorg/radare2) .

CBMC version: **goto-cc 5.12 (cbmc-5.12-d8598f8-1166-gaca06bd9e) 64-bit**
Operating system: Manjaro
Exact command line resulting in the issue: goto-cc example.c
What behaviour did you expect: program gets compiled
What happened instead:  compilation error

**Comment by kroening** [comment]
Many thanks for reporting -- I've made a PR with a KNOWNBUG test.

**Comment by kroening** [comment]
#5154 now has a candidate bugfix.

**Comment by tautschnig** [comment]
Fixed via #5154.
