### ISSUE TITLE
CBMC does not build with clang on ubuntu 22.04

### ISSUE THREAD

**Issue by esteffin** [diffblue/cbmc#7366]
Building CBMC with `clang` on `ubuntu 22.04` fails.

The issue is that during the compilation of target `library-check.stamp` at step `Checking /root/cbmc/src/ansi-c/library/stdio.c` there is an error:
```
__libcheck.c:859:5: error: definition with same mangled name '__isoc99_fscanf' as another definition
int __isoc99_fscanf
```

The issue happens with `clang-11`, `clang-12` and `clang-13`.

The build using `gcc` instead works.

CBMC version: commit d932d6ffded15019b7591b025f22e8e072c58a52
Operating system: Ubuntu 22.04
Exact command line resulting in the issue: `make`
What behaviour did you expect: A correct build
What happened instead: Error during build

**Comment by esteffin** [comment]
After a bit of investigation it seems that the script `src/ansi-c/library_check.sh` fails when checking `stdio.c` as clang cannot build it on Ubuntu 22.04.

On Mac the compilation with `clang-12` instead is successful.

**Comment by tautschnig** [comment]
We should probably `#ifndef` the non `__isoc99_` variants when `__clang__` is set.

**Comment by tautschnig** [comment]
To be fixed as part of #7496.
